### ISSUE TITLE
Not working with Radeon HD

### ISSUE THREAD

**Issue by leviathan69** [arunsatyarth/OneMiner#17]
I love your software but it is not working with my current graphics card. Is it just that the graphics card I have is outdated, or is there something I can do to make it work? 
Oneminer tells me it is an AMD Radeon HD 7560D and in the cmd screen there are messages saying 'not enough GPU memory to place DAG, you cannot mine coin with this GPU' and 'open CL error -61 cannot allocate big buffer for DAG' being quite new to this I would be grateful for anything you could suggest to help. Many thanks

**Comment by arunsatyarth** [comment]
Yes unfortunately Ethhash based coins require minimum 1 GB RAM in graphics card. Ethereum & Ethereum Classic  requires at least 3 GB RAM. You could try once with Ubiq or Expanse.
STEPS: 
 Click Add Miner and select Ubiq/Expanse from the list.
 Fill in the Wallet/Pool  details.
 Do not click on "Add Dual miner".
 Finish and click Start.

**Comment by arunsatyarth** [comment]
Also I believe mining wouldn't be as profitable on that card as the power consumption would outweigh the profits.

**Comment by leviathan69** [comment]
Thanks for getting back to me, much appreciated

**Comment by arunsatyarth** [comment]
Anytime...
