### ISSUE TITLE
One Miner Still Starting When "Launch On Startup" Is set to no

### ISSUE THREAD

**Issue by m-henderson** [arunsatyarth/OneMiner#26]

**Comment by arunsatyarth** [comment]
This setting basically sets a Key in the following path after you open registry with regedit.
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
The key name used is 'OneMiner'. Could you check if a setting is being created and deleted, when you switch between Yes and No. You will have to press F5 to refresh registry UI.
Also, which windows OS is this?

**Comment by m-henderson** [comment]
@arunsatyarth yes, I can check this. I am running windows 10 pro.

**Comment by m-henderson** [comment]
It looks like it is removing the key as it should and it is adding it as it should. Let me test this to make sure I didn't accidentally have it checked.

**Comment by arunsatyarth** [comment]
Did you get a chance to test the hypothesis that its being accidentally checked?

**Comment by m-henderson** [comment]
@arunsatyarth yea, everything is working normally. we can close this issue.
